# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: dummy-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: dummy-app
#   template:
#     metadata:
#       labels:
#         app: dummy-app
#     spec:
#       containers:
#       - name: dummy-app
#         image: python:3.9-slim
#         command: ["/bin/sh"]
#         args: ["-c", "python3 /app/app.py"]
#         ports:
#         - containerPort: 8000
#         volumeMounts:
#         - name: app-code
#           mountPath: /app
#       volumes:
#       - name: app-code
#         hostPath:
#           path: /home/ubuntu/app
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: dummy-app-service
# spec:
#   type: NodePort
#   ports:
#   - port: 8000
#     targetPort: 8000
#     nodePort: 30001
#   selector:
#     app: dummy-app

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        image: dummy-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-app-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
  selector:
    app: dummy-app